Refactor `WormholeProvider`
LeastAuthority/winden pull request #93
Opened 2022-12-02 07:30 UTC by JustusFT

2022-12-02 13:34 UTC, donpui commented
If we are getting rid of worker, we need to cleanup in gulpfile.js and Dockerfile as there are some tasks defined.

2022-12-22 13:28 UTC, donpui commented
@JustusFT I have issue, that I cannot download file, when I use url on receiver side: http://localhost:8080/#6-backwater-southward. 
If I enter code manually, download works.

2022-12-22 13:51 UTC, donpui commented on client/src/app/components/providers/WormholeProvider.tsx
> +      step: "confirming" | "inProgress" | "failed" | "succeeded";
Should we have rejection/cancellation step?

2022-12-22 15:39 UTC, donpui commented
One more error, not handled case when  `Nameplate is unclaimed: 14`.

2022-12-22 15:51 UTC, donpui requested changes
I have pushed small gulpfile changes, however we need to address other issues too.

Overall simplification is good here. However I am think, that in future we might (or not) get back to worker, when dilation might appear, especially if we want several files sending simultaneously or keep them in background and allowing navigate in app. But may be it is easier to start with worker from fresh with specific features which we want to achieve, then what we have now.

2023-01-03 13:42 UTC, donpui commented
After discussion with @JustusFT we agreed to close this PR, as it requires more dev and testing effort to finalise, however with dilation, we might still need to get back to worker. Closing PR, but keeping branch for future work.

2023-01-03 13:42 UTC, closed without merging

2023-01-04 18:53 UTC, meejah commented
Is there ticket describing what this PR was / is trying to achieve (so that when/if we do revisit it, some context can be obtained without reading all ~2000 LoC of the PR)?